Suhyun:12월 4주차
YunWonYong/Programmers pull request #139
Opened 2021-12-23 12:05 UTC by suhyun96

내림차순 정렬은 자바 도저히 안풀려서 검색했습니다.

2021-12-23 12:16 UTC, nattybear commented
> 내림차순 정렬은 자바 도저히 안 풀려서 검색했습니다.

검색도 능력입니다 ㅎ

2021-12-23 12:24 UTC, nattybear commented on Suhyun/Java/PtoY.java
> +            if (arr[i] == 80 || arr[i] == 112) {
대문자나 소문자로 통일하지 않고 그냥 이렇게 숫자로 검사하셨군요 ㅎ 신박하네요 ㅎ

2021-12-23 12:28 UTC, nattybear requested changes
문제가 요구하는 함수 형식을 지켜 주세요.

* 보통 문제가 요구하는 해답의 함수 이름은 `solution` 입니다.
* 함수 인자의 이름까지 문제가 제시한대로 따라할 필요는 없습니다.
* 정적 타입 언어인 경우 ~~함수 인자와~~ 리턴 값의 타입을 지켜야 합니다.

2021-12-23 13:11 UTC, YunWonYong reviewed
초큼 더 해보시죵 ㅎㅎ

2021-12-23 13:11 UTC, YunWonYong commented on Suhyun/Java/PtoY.java
> +            }
이건 스위치 문으로 하는게 더 좋을 것 같네요 ㅎㅎ

```java
switch(arr[i]){
    case 89:
    case 121:
        y_count++;
    break;
    case 80:
    case 112:
        p_count++;
    break;
}
```

2021-12-23 13:11 UTC, YunWonYong commented on Suhyun/Java/Omoikiri.java
> +        }
아~ n번의 문자를 prefix로 붙여 ArrayList에 넣은 후 정렬하고 다시 prefix를 제거했군요!
하지만 문제는
* n번 문자를 기준으로 정렬 후
* n번 문자가 같은 문자열들을 사전 순으로 정렬하는 문제

아직 시간 있으니까 조금 더 고민해 보시면 어떨까요 ? :)

도저히 못 푸시겠으면 제가 도와드리겠습니다 :)

2021-12-23 13:18 UTC, YunWonYong approved these changes
수고하셨습니다 :)

2021-12-23 13:18 UTC, YunWonYong commented on Suhyun/Java/Omoikiri.java
> +        }
아~ 통과하시고 올려 주신 거구나 !! ㅎㅎ

2021-12-23 13:22 UTC, YunWonYong commented
> 문제가 요구하는 함수 형식을 지켜 주세요.
> 
> * 보통 문제가 요구하는 해답의 함수 이름은 `solution` 입니다.
> * 함수 인자의 이름까지 문제가 제시한대로 따라할 필요는 없습니다.
> * 정적 타입 언어인 경우 함수 인자와 리턴 값의 타입을 지켜야 합니다.

정적 타입 언어인 경우 함수 인자와 리턴 값의 타입을 지켜야 합니다.
이건 아닙니다. 문제 중 반환 타입이 int인데 오버플로우로 인해 int에서 long으로 변경 해야 할 때도 있습니다. :)

그런데 의문이 왜 1번과 2번을 강제하시나요? 
이런 것을 편하게 하기 위해 브랜치별로 나눴는데 강제하시면 쫌 모순이라 생각되네요 ?

2021-12-23 13:35 UTC, nattybear commented
@YunWonYong 프로그래머스 사이트에 제출 가능한 상태는 지켜야 한다고 생각합니다.

2021-12-23 13:38 UTC, nattybear commented
@YunWonYong 문제가 요구한 반환 타입이 `int`인데 `long`으로 변환해야 했던 문제 이름을 알 수 있을까요?

2021-12-23 13:40 UTC, YunWonYong commented
@nattybear 그렇게 말씀하시면 Haskell언어로 코딩하신 파일도 올리시면 안될 것 같은데
이유는 프로그래머스 사이트에 하스켈 언어를 지원하는 문제도 없기 때문입니다.

그리고 준규님이 말씀하신 내용 중 "다른 사람들 코드파일을 컴파일할 일 없다" 라고 말씀하셨었는데 
제 생각엔 문제가 안된다 생각됩니다.

부족한 금액 계산하기 입니다.
https://programmers.co.kr/learn/courses/30/lessons/82612

2021-12-23 13:45 UTC, suhyun96 commented on Suhyun/Java/PtoY.java
> +            }
그렇네요!

2021-12-23 13:47 UTC, nattybear commented
@YunWonYong `부족한 금액 계산하기` 에서는 문제가 반환 타입으로 `long`을 제시합니다.

2021-12-23 13:49 UTC, YunWonYong commented
@nattybear 저도 글 쓰고 확인해봤는데 제가 착각했었네요 answer 변수를 int로 한 후 오버플로어 때문에 못 푼 걸 반환 타입 때문이라고 착각했네요 죄송합니다.

2021-12-23 13:51 UTC, nattybear commented
@YunWonYong 최근에 원용님께서 코드 리뷰 시 수정 요청 기능이 있다는 걸 알려주셔서 한번 해보자는 의미로 함수 프로토콜을 맞춰 달라고 ***제안*** 해보았습니다.

지키지 않으셔도 됩니다.

2021-12-23 13:59 UTC, nattybear approved these changes
제 요청을 반영 해 주셔서 감사합니다.

로컬에서 테스트를 할 때 저는 아래와 같이 테스트 클래스를 따로 만듭니다.

```java
public class Main {
  public static void main(String[] args) {
    Solution s = new Solution();
    Sytem.out.println(s.solution());
  }
}```

2021-12-23 14:04 UTC, suhyun96 commented
> 제 요청을 반영 해 주셔서 감사합니다.
> 
> 로컬에서 테스트를 할 때 저는 아래와 같이 테스트 클래스를 따로 만듭니다.
> 
> ```java
> public class Main {
>   public static void main(String[] args) {
>     Solution s = new Solution();
>     System.out.println(s.solution(...));
>   }
> }
> ```아 그렇군요. 저는 로컬에서 작업하고 알맹이만 프로그래머스에 동작하도록 바꾸고 제출하고 있어요. 
이번에는 커밋할 때 알맹이만 올려서 찝찝하던 차에 지적해주셔서 고쳤습니다.

2021-12-23 14:06 UTC, suhyun96 commented on Suhyun/Java/Omoikiri.java
> +        }
아이디어는 찾았었는데 구현을 못했었는데 바로 나오더라구요 . 
다른 방식도 생각해보겠습니다

2021-12-23 14:08 UTC, nattybear commented
@suhyun96 JavaScript도 제출 코드와 테스트 코드를 정확히 분리하고 싶어서 `export`를 알아봤는데요

프로그래머스에 `export` 코드를 제출하면 에러가 나서 포기했습니다 ㅎ

2021-12-23 14:10 UTC, Lee-jh01 approved these changes
수고하셨습니다:)

2021-12-23 14:15 UTC, Lee-jh01 commented on Suhyun/Java/PtoY.java
> +                    break;
저는 string.toLoswercase(); 함수를 썼는데, 편리한 점은 있지만 이 코드가 더 효율성 좋아 보이네요

2021-12-24 00:13 UTC, gmake20 approved these changes

2021-12-24 00:13 UTC, gmake20 commented on Suhyun/Java/PtoY.java
> +        if (y_count == 0 && p_count == 0||y_count == p_count) {
if (y_count == p_count) {
이렇게 해도 되지 않을까요?

2021-12-24 00:27 UTC, nattybear commented on Suhyun/JS/PtoY.js
> +    {
`P`와 `Y`는 변수가 아니라 문자열로 사용하시려는 의도였을 것 같습니다. 이 코드는 `Outdated` 된 것이고 [최종 코드](https://github.com/suhyun96/Programmers/blob/master/Suhyun/JS/PtoY.js)에서는 문자열로 수정이 되어 있네요 ㅎ 수현님은 fork를 하신 후에 PR을 하셨네요 ㅎ

2021-12-24 03:39 UTC, suhyun96 commented on Suhyun/Java/PtoY.java
> +        if (y_count == 0 && p_count == 0||y_count == p_count) {
맞네요! 감사합니다!

2021-12-24 03:40 UTC, suhyun96 commented on Suhyun/JS/PtoY.js
> +    {
포크 뜬 다음 PR 하는게 본 레포지토리에 덜 영향 준다고 들어서 이렇게 하고 있어요. 
이상한 점 있으면 알려주세요!

2021-12-24 03:40 UTC, merged

2021-12-24 04:26 UTC, nattybear commented on Suhyun/JS/PtoY.js
> +    {
이상하지 않습니다. 스스로 브랜치 관리를 해 볼 수 있다는 점에서 fork가 더 좋은 방법이라고 생각합니다.