Andy
YunWonYong/Programmers pull request #90
Opened 2021-11-21 15:24 UTC by gmake20

2021-11-22 #86 clear, #87 clear, #88 clear
프로그래머스 Level 1, 2016년
프로그래머스 Level 1, 예산
프로그래머스 Level 1, 두 개 뽑아서 더하기

2021-11-21 23:20 UTC, YunWonYong requested changes
Algorithms/src/andy/javascript/level1/twopickplus.js 이 파일이랑
Algorithms/src/andy/javascript/level1/budget.js 이 파일 내용이 같은거 같습니다 ㅎㅎ

2021-11-22 11:37 UTC, nattybear approved these changes
수고하셨습니다 ㅎ

2021-11-22 12:47 UTC, gmake20 commented
@YunWonYong 
헐..정말 파일내용이 같네요.
수정했습니다~~

2021-11-22 15:40 UTC, YunWonYong approved these changes
수고하셨습니다 :)

2021-11-25 13:56 UTC, merged